### PR TITLE
Make my_node_id() work with Elasticsearch 1.x.

### PR DESCRIPTION
**Pull request by magnusbaeck**
Elasticsearch 1.0.0 replaced the /_cluster/nodes endpoint with
/_nodes. Check which version we're dealing with and choose the
correct API when trying to obtain the node id of the local node
in my_node_id().

### CODE REVIEW

**Comment by olorin** [comment]
Thanks for this. When I get some time I need to go through this module and add tests for 1.x compatibility.

**Comment by magnusbaeck** [comment]
Thanks for the quick review! Will you also make a new PyPI release of the library?

**Comment by olorin** [comment]
I will, as soon as I've had a chance to test it out on a couple of different ES versions (it looks fine to me and works on my local 1.x, just want to make sure versions <1 don't offer any surprises); I should be able to do a release today (next twelve hours).

**Comment by olorin** [comment]
Apologies for the delay; v1.0.1 has been released and uploaded to PyPI.

**Comment by magnusbaeck** [comment]
No problem. Thank you very much!

**Pull request merged**
